ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS ux_design_status VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
  ADD COLUMN IF NOT EXISTS technical_design_status VARCHAR(20) NOT NULL DEFAULT 'LOCKED',
  ADD COLUMN IF NOT EXISTS ux_design_completed_at TIMESTAMP;
